import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Replay } from './Replay';

/* ---------------------------------------------------------------- types */
type Play = {
  durationSec: number;
  direction: 'BUY' | 'SELL';
  multiplier: number;
  entryPrice: number;
  stopOutPrice: number;
  takeProfitPrice: number;
  exitPrice: number;
  profitPerUnit: number;
  reason: 'EXPIRY' | 'STOP_OUT' | 'TAKE_PROFIT';
  ticks: number;
};

type Oracle = {
  symbol: string;
  name: string;
  now: number;
  tickMs: number;
  price: number;
  epoch: {
    epoch: number;
    seed: string;
    seedHash: string;
    nextSeedHash: string;
    startPrice: number;
    startedAt: number;
    endsAt: number;
    tickIndex: number;
    ticksPerEpoch: number;
  };
  recent: Array<{ at: number; price: number }>;
  future: Array<{ at: number; price: number }>;
  plays: Play[];
  best: Play | null;
};

type OpenPosition = {
  id: string;
  symbol: string;
  direction: 'BUY' | 'SELL';
  stake: number;
  durationSec: number;
  multiplier: number;
  entryPrice: number;
  stopOutPrice: number;
  takeProfitPrice: number;
  maxProfit: number;
  openedAt: number;
  settlesAt: number;
  predicted: { profit: number; reason: Play['reason'] };
};

type ClosedPosition = OpenPosition & {
  status: 'WON' | 'LOST';
  exitPrice: number | null;
  profit: number | null;
  closeReason: Play['reason'] | null;
};

type State = {
  balance: number;
  startingBalance: number;
  open: OpenPosition[];
  closed: ClosedPosition[];
  forecastAccuracy: { checked: number; matched: number } | null;
  instruments: Array<{ symbol: string; name: string; volatility: number; price: number }>;
  durations: number[];
  maxProfitMultiple: number;
  houseEdge: number;
};

/* -------------------------------------------------------------- helpers */
const nf = new Intl.NumberFormat('en-KE', { maximumFractionDigits: 2 });
const ksh = (n: number): string =>
  (n < 0 ? '−' : '') + 'KSh ' + nf.format(Math.abs(Number.isFinite(n) ? n : 0));

const REASON_LABEL: Record<Play['reason'], string> = {
  EXPIRY: 'runs to expiry',
  STOP_OUT: 'stops out',
  TAKE_PROFIT: 'hits the cap',
};

async function call<T>(path: string, body?: unknown): Promise<T> {
  const res = await fetch('/api/sandbox' + path, {
    method: body === undefined ? 'GET' : 'POST',
    headers: body === undefined ? undefined : { 'Content-Type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
    credentials: 'same-origin',
  });
  const text = await res.text();
  const data = text ? (JSON.parse(text) as unknown) : null;
  if (!res.ok) {
    const message = (data as { message?: string } | null)?.message ?? 'Request failed.';
    throw new Error(message);
  }
  return data as T;
}

/* ----------------------------------------------------------------- gate */
function Gate({ onIn }: { onIn: () => void }): JSX.Element {
  const [passphrase, setPassphrase] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const submit = (e: FormEvent): void => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    void call('/login', { passphrase })
      .then(onIn)
      .catch((err: Error) => setError(err.message))
      .finally(() => setBusy(false));
  };

  return (
    <div className="gate">
      <form className="gate-card" onSubmit={submit}>
        <div className="gate-mark">SANDBOX</div>
        <h1>Fpesa Sandbox</h1>
        <p>
          A throwaway market with its seed on display. Its prices are generated by
          this server and have nothing to do with fpesa.markets. No accounts, no
          deposits, no money — the balance here is a number in memory that
          disappears when the service restarts.
        </p>
        <label>
          <span>Passphrase</span>
          <input
            type="password"
            value={passphrase}
            autoComplete="current-password"
            onChange={(e) => setPassphrase(e.target.value)}
          />
        </label>
        {error && <div className="err">{error}</div>}
        <button className="btn primary" disabled={busy || passphrase.length === 0}>
          {busy ? 'Checking…' : 'Open the sandbox'}
        </button>
      </form>
    </div>
  );
}

/* ---------------------------------------------------------------- chart */
/**
 * Recent path solid, the path still to come dashed, with the barriers of
 * whichever play is selected drawn across both.
 *
 * Hand-rolled rather than a charting library because no charting library draws
 * the future — that overlay is the entire reason this screen exists, and a
 * polyline is a dozen lines of code.
 */
function Chart({
  oracle,
  play,
}: {
  oracle: Oracle;
  play: Play | null;
}): JSX.Element {
  const W = 900;
  const H = 280;
  const PAD = 8;

  const series = useMemo(() => {
    const past = oracle.recent.map((p) => p.price);
    const ahead = oracle.future.map((p) => p.price);
    return { past, ahead, all: [...past, ...ahead] };
  }, [oracle]);

  const bounds = useMemo(() => {
    const values = [...series.all];
    if (play) values.push(play.stopOutPrice, play.takeProfitPrice, play.entryPrice);
    const lo = Math.min(...values);
    const hi = Math.max(...values);
    // A flat window would divide by zero; pad it to something drawable.
    const span = hi - lo || Math.max(hi * 0.0001, 0.01);
    return { lo: lo - span * 0.08, hi: hi + span * 0.08 };
  }, [series, play]);

  const n = series.all.length;
  const x = (i: number): number => PAD + (i / Math.max(n - 1, 1)) * (W - PAD * 2);
  const y = (v: number): number =>
    PAD + (1 - (v - bounds.lo) / (bounds.hi - bounds.lo)) * (H - PAD * 2);

  const pastPath = series.past.map((v, i) => x(i) + ',' + y(v)).join(' ');
  const aheadPath = series.ahead
    .map((v, i) => x(series.past.length - 1 + i + 1) + ',' + y(v))
    .join(' ');
  // Joins the two so there is no visible gap at the boundary.
  const joint =
    series.past.length > 0 && series.ahead.length > 0
      ? x(series.past.length - 1) + ',' + y(series.past[series.past.length - 1]!) + ' '
      : '';
  const nowX = x(Math.max(series.past.length - 1, 0));
  const closeX = play ? x(series.past.length - 1 + Math.min(play.ticks, series.ahead.length)) : null;

  return (
    <div className="chart-wrap">
      <svg viewBox={'0 0 ' + W + ' ' + H} className="chart" preserveAspectRatio="none">
        {play && (
          <>
            <line x1={PAD} x2={W - PAD} y1={y(play.takeProfitPrice)} y2={y(play.takeProfitPrice)}
              className="lv lv-tp" />
            <line x1={PAD} x2={W - PAD} y1={y(play.entryPrice)} y2={y(play.entryPrice)}
              className="lv lv-entry" />
            <line x1={PAD} x2={W - PAD} y1={y(play.stopOutPrice)} y2={y(play.stopOutPrice)}
              className="lv lv-so" />
          </>
        )}

        {/* Everything right of this line has not happened yet. */}
        <rect x={nowX} y={PAD} width={Math.max(W - PAD - nowX, 0)} height={H - PAD * 2}
          className="future-wash" />
        <line x1={nowX} x2={nowX} y1={PAD} y2={H - PAD} className="now-line" />
        {closeX !== null && (
          <line x1={closeX} x2={closeX} y1={PAD} y2={H - PAD} className="close-line" />
        )}

        <polyline points={pastPath} className="line-past" />
        <polyline points={joint + aheadPath} className="line-ahead" />
      </svg>

      <div className="chart-legend">
        <span><i className="sw sw-past" /> already happened</span>
        <span><i className="sw sw-ahead" /> still to come</span>
        {play && <span><i className="sw sw-tp" /> profit cap</span>}
        {play && <span><i className="sw sw-so" /> stop-out</span>}
        {closeX !== null && play && (
          <span><i className="sw sw-close" /> closes in {(play.ticks * oracle.tickMs / 1000).toFixed(2)}s</span>
        )}
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ app */
export function App(): JSX.Element {
  const [authed, setAuthed] = useState<boolean | null>(null);
  const [symbol, setSymbol] = useState<string | null>(null);
  const [oracle, setOracle] = useState<Oracle | null>(null);
  const [state, setState] = useState<State | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [stake, setStake] = useState('1000');
  const [duration, setDuration] = useState(10);
  const [busy, setBusy] = useState(false);
  const [seedOpen, setSeedOpen] = useState(false);
  const [view, setView] = useState<'live' | 'replay'>('live');

  // Held in a ref so the polling effect does not restart on every tick.
  const symbolRef = useRef<string | null>(null);
  symbolRef.current = symbol;

  useEffect(() => {
    void call<{ authenticated: boolean }>('/session')
      .then((r) => setAuthed(r.authenticated))
      .catch(() => setAuthed(false));
  }, []);

  const loadState = useCallback(async () => {
    const s = await call<State>('/state');
    setState(s);
    if (!symbolRef.current && s.instruments.length) {
      setSymbol(s.instruments[0]!.symbol);
    }
  }, []);

  const loadOracle = useCallback(async () => {
    const s = symbolRef.current;
    if (!s) return;
    setOracle(await call<Oracle>('/oracle?symbol=' + encodeURIComponent(s)));
  }, []);

  // Two ticks a second. The market moves four times a second, so this is
  // smooth enough to read without making a request per tick. Paused on the
  // replay view, which is studying a fixed epoch and has nothing to refresh.
  useEffect(() => {
    if (!authed || view !== 'live') return;
    let alive = true;
    const run = (): void => {
      void Promise.all([loadOracle(), loadState()])
        .then(() => alive && setError(null))
        .catch((err: Error) => alive && setError(err.message));
    };
    run();
    const id = window.setInterval(run, 500);
    return () => {
      alive = false;
      window.clearInterval(id);
    };
  }, [authed, view, loadOracle, loadState]);

  // Replay needs the instrument list too, and on that view the poll above is
  // switched off, so fetch it once on arrival.
  useEffect(() => {
    if (authed && view === 'replay' && !state) void loadState().catch(() => undefined);
  }, [authed, view, state, loadState]);

  const trade = (direction: 'BUY' | 'SELL'): void => {
    if (!symbol) return;
    setBusy(true);
    void call<State>('/trade', { symbol, direction, stake: Number(stake), durationSec: duration })
      .then((s) => {
        setState(s);
        setError(null);
      })
      .catch((err: Error) => setError(err.message))
      .finally(() => setBusy(false));
  };

  if (authed === null) return <div className="boot">Loading…</div>;
  if (!authed) return <Gate onIn={() => setAuthed(true)} />;

  const stakeAmount = Number(stake);
  // The play the trade ticket currently describes, for the chart and the button
  // labels. Both sides are shown, so the screen never hides the losing one.
  const ticket = oracle?.plays.filter((p) => p.durationSec === duration) ?? [];
  const buy = ticket.find((p) => p.direction === 'BUY') ?? null;
  const sell = ticket.find((p) => p.direction === 'SELL') ?? null;
  const better = !buy || !sell ? (buy ?? sell) : buy.profitPerUnit >= sell.profitPerUnit ? buy : sell;

  return (
    <>
      {/* Fixed, loud, and never dismissible. Someone landing on this screen must
          not be able to mistake it for the platform that takes deposits. */}
      <div className="warn-bar">
        SANDBOX · these prices are generated by this server · not fpesa.markets ·
        no real money
      </div>

      <header className="top">
        <div className="brand">
          Fpesa <span>Sandbox</span>
        </div>
        <div className="top-right">
          <div className="bal">
            <span className="k">Paper balance</span>
            <b>{state ? ksh(state.balance) : '—'}</b>
          </div>
          <button
            className="btn ghost"
            onClick={() => void call('/reset', {}).then(loadState).catch(() => undefined)}
          >
            Reset
          </button>
          <button
            className="btn ghost"
            onClick={() => void call('/logout', {}).then(() => setAuthed(false))}
          >
            Lock
          </button>
        </div>
      </header>

      <main className="wrap">
        <nav className="views">
          <button aria-pressed={view === 'live'} onClick={() => setView('live')}>
            Live sandbox
          </button>
          <button aria-pressed={view === 'replay'} onClick={() => setView('replay')}>
            Replay
          </button>
        </nav>

        {error && <div className="err">{error}</div>}

        <nav className="markets">
          {/* Defensive even though the server now always sends it: a missing
              field here blanks the whole screen, and the screen is the product. */}
          {(state?.instruments ?? []).map((i) => (
            <button
              key={i.symbol}
              aria-pressed={i.symbol === symbol}
              onClick={() => setSymbol(i.symbol)}
            >
              <b>{i.symbol}</b>
              <span>{nf.format(i.price)}</span>
            </button>
          ))}
        </nav>

        {view === 'replay' && <Replay symbol={symbol} />}

        {view === 'live' && oracle && (
          <>
            <section className="headline">
              <div>
                <div className="k">{oracle.name}</div>
                <div className="price">{nf.format(oracle.price)}</div>
              </div>
              {oracle.best && (
                <div className="best">
                  <div className="k">Best position available right now</div>
                  <div className="best-v">
                    <span className={'side ' + oracle.best.direction.toLowerCase()}>
                      {oracle.best.direction}
                    </span>
                    <span className="dur">{oracle.best.durationSec}s</span>
                    <span className="gain">
                      +{ksh(oracle.best.profitPerUnit * 1000)} per KSh 1,000
                    </span>
                  </div>
                  <div className="k">
                    {REASON_LABEL[oracle.best.reason]} after{' '}
                    {(oracle.best.ticks * oracle.tickMs / 1000).toFixed(2)}s
                  </div>
                </div>
              )}
            </section>

            <Chart oracle={oracle} play={better} />

            {/* The ticket. Both sides carry their own outcome, because showing
                only the winning one would turn a demonstration into a pitch. */}
            <section className="ticket">
              <div className="field">
                <span className="k">Stake</span>
                <input
                  inputMode="decimal"
                  value={stake}
                  onChange={(e) => setStake(e.target.value.replace(/[^0-9.]/g, ''))}
                />
              </div>
              <div className="field">
                <span className="k">Duration</span>
                <div className="durs">
                  {(state?.durations ?? []).map((d) => (
                    <button key={d} aria-pressed={d === duration} onClick={() => setDuration(d)}>
                      {d}s
                    </button>
                  ))}
                </div>
              </div>
              <div className="sides">
                {([buy, sell] as Array<Play | null>).map(
                  (p) =>
                    p && (
                      <button
                        key={p.direction}
                        className={'side-btn ' + p.direction.toLowerCase() +
                          (p.profitPerUnit >= 0 ? ' wins' : ' loses')}
                        disabled={busy || !Number.isFinite(stakeAmount) || stakeAmount <= 0}
                        onClick={() => trade(p.direction)}
                      >
                        <b>{p.direction}</b>
                        <span className="outcome">
                          {p.profitPerUnit >= 0 ? '+' : '−'}
                          {ksh(Math.abs(p.profitPerUnit * (stakeAmount || 0)))}
                        </span>
                        <small>{REASON_LABEL[p.reason]} in {(p.ticks * oracle.tickMs / 1000).toFixed(2)}s</small>
                      </button>
                    )
                )}
              </div>
            </section>

            <section className="grid-sec">
              <h2>Every position open to you, and what each one does</h2>
              <div className="scroll">
                <table className="plays">
                  <thead>
                    <tr>
                      <th>Duration</th>
                      <th>Side</th>
                      <th>Entry</th>
                      <th>Exit</th>
                      <th>Closes</th>
                      <th>How it ends</th>
                      <th>Per KSh 1,000</th>
                    </tr>
                  </thead>
                  <tbody>
                    {oracle.plays.map((p) => (
                      <tr
                        key={p.durationSec + p.direction}
                        className={p === oracle.best ? 'pick' : ''}
                      >
                        <td>{p.durationSec}s</td>
                        <td className={'side ' + p.direction.toLowerCase()}>{p.direction}</td>
                        <td>{nf.format(p.entryPrice)}</td>
                        <td>{nf.format(p.exitPrice)}</td>
                        <td>{(p.ticks * oracle.tickMs / 1000).toFixed(2)}s</td>
                        <td className="reason">{REASON_LABEL[p.reason]}</td>
                        <td className={p.profitPerUnit >= 0 ? 'up' : 'down'}>
                          {p.profitPerUnit >= 0 ? '+' : '−'}
                          {ksh(Math.abs(p.profitPerUnit * 1000))}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="note">
                The spread is charged on both sides, so with the market standing
                still every row here would be a loss of{' '}
                {state ? (state.houseEdge * 100).toFixed(1) : '—'}% of the stake.
                A row showing a profit is showing one that survived that cost.
              </p>
            </section>

            <section className="grid-sec">
              <button className="seed-toggle" onClick={() => setSeedOpen((v) => !v)}>
                {seedOpen ? '▾' : '▸'} The seed this all comes from
              </button>
              {seedOpen && (
                <div className="seed">
                  <p className="note">
                    On the live platform the hash below is published while the epoch
                    runs and the seed only once it has closed — that is what proves
                    prices were not changed after the fact. It cannot prove they
                    were not <em>known</em>, and this panel is what knowing looks
                    like. The seed is shown here because this market has no
                    customers; on a market with customers, holding it is the whole
                    problem.
                  </p>
                  <dl>
                    <dt>Epoch</dt>
                    <dd>
                      {oracle.epoch.epoch} · tick {oracle.epoch.tickIndex} of{' '}
                      {oracle.epoch.ticksPerEpoch}
                    </dd>
                    <dt>Opening price</dt>
                    <dd>{nf.format(oracle.epoch.startPrice)}</dd>
                    <dt>Seed</dt>
                    <dd className="mono">{oracle.epoch.seed}</dd>
                    <dt>SHA-256 of it</dt>
                    <dd className="mono">{oracle.epoch.seedHash}</dd>
                    <dt>Next epoch&rsquo;s commitment</dt>
                    <dd className="mono">{oracle.epoch.nextSeedHash}</dd>
                  </dl>
                </div>
              )}
            </section>
          </>
        )}

        {view === 'live' && state && (state.open.length > 0 || state.closed.length > 0) && (
          <section className="grid-sec">
            <h2>
              Your positions
              {state.forecastAccuracy && (
                <span className="tally">
                  forecast matched the result on {state.forecastAccuracy.matched} of{' '}
                  {state.forecastAccuracy.checked}
                </span>
              )}
            </h2>

            {state.open.map((p) => (
              <div key={p.id} className="pos open">
                <span className={'side ' + p.direction.toLowerCase()}>{p.direction}</span>
                <span>{p.symbol} · {p.durationSec}s · {ksh(p.stake)}</span>
                <span className="muted">
                  settles in {Math.max((p.settlesAt - Date.now()) / 1000, 0).toFixed(1)}s
                </span>
              </div>
            ))}

            {state.closed.map((p) => {
              const matched =
                p.predicted.reason === p.closeReason &&
                Math.abs((p.profit ?? 0) - p.predicted.profit) <= 0.01;
              return (
                <div key={p.id} className={'pos ' + (p.status === 'WON' ? 'won' : 'lost')}>
                  <span className={'side ' + p.direction.toLowerCase()}>{p.direction}</span>
                  <span>{p.symbol} · {p.durationSec}s · {ksh(p.stake)}</span>
                  <span className={p.status === 'WON' ? 'up' : 'down'}>
                    {(p.profit ?? 0) >= 0 ? '+' : '−'}{ksh(Math.abs(p.profit ?? 0))}
                  </span>
                  <span className="muted">{p.closeReason && REASON_LABEL[p.closeReason]}</span>
                  {/* The forecast is only worth something if it can be checked,
                      so it is shown next to what actually happened. */}
                  <span className={matched ? 'chip ok' : 'chip off'}>
                    {matched ? 'as forecast' : 'forecast ' + ksh(p.predicted.profit)}
                  </span>
                </div>
              );
            })}
          </section>
        )}

        <footer className="foot">
          <p>
            <b>This is not a predictor for fpesa.markets.</b> The seeds above were
            generated by this process when it started and are not the live
            platform&rsquo;s. The live seed is not returned by any endpoint while
            its epoch is open, and nothing here can reach it — same code, different
            random numbers. There is also nothing to learn from watching: the path
            is a driftless random walk, and the only reason it is knowable here is
            that the secret is being handed over on purpose.
          </p>
        </footer>
      </main>
    </>
  );
}
